#!/usr/bin/perl

my $i = 0;

print "/* AUTOGENERATED; DO NOT MODIRY */\n";
print "static op_handler_t handlers[256] = {\n";

while (<STDIN>) {

	my @a = split(" ", $_);

	if ($i != $a[0]) {
		while ($i != $a[0]) {
			print "handle_invalid,\n";
			$i += 1;
		}
	} 

	print "handle_$a[2],\n";

	$i += 1;

}

print "};\n";
